### ISSUE TITLE
Use twopi or circo instead of dot

### ISSUE THREAD

**Issue by markferry** [magma1447/HomeAssistant-Zwave-ConnectionMap#2]
The default layout for the PHP Graphviz plugin appears to be 'dot' which is suited for strictly hierarchical (or partially-ordered) graphs.

Consider using twopi ([example](https://graphviz.gitlab.io/_pages/Gallery/twopi/twopi2.html)) or circo [layouts](https://www.graphviz.org/about/) instead.

:)

**Comment by magma1447** [comment]
It's likely that I won't maintain this anymore. https://github.com/OmenWild/home-assistant-z-wave-graph was created by inspiration from this, and another project. Since it's correctly integrated with Home Assistant, I will switch to that when I have the time.

I did install it when it was new, but there were so many changes back then that I put it on hold. Since then I have just not prioritized it again. But you should look into that.
